From node:12.16.1-alpine3.11 as builder

WORKDIR /app
COPY . .
#RUN npm install --registry=https://registry.npm.taobao.org \
RUN SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install --registry=http://registry.npm.dev.com:5873 \
        && npm run build



From nginx:1.17.6-alpine
ENV TZ=Asia/Shanghai

#COPY dist/ /usr/share/nginx/html/
COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY nginx /etc/nginx/
COPY docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh \
        && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
        && apk add --no-cache curl tzdata \
        && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo "$TZ" > /etc/timezone

HEALTHCHECK --interval=50s --timeout=3s \
  CMD curl -kf https://localhost || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
